---
version: 1

build_arg_defaults:
  EE_BUILDER_IMAGE: registry.redhat.io/ansible-automation-platform-24/ansible-builder-rhel8:latest
  EE_BASE_IMAGE: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest

ansible_config: ansible.cfg

dependencies:
  galaxy: requirements.yaml
  python: requirements.txt
  system: bindep.txt

additional_build_steps:
  prepend: []
  append: []
